export const FETCH_EVENT_FEED = "FETCH_EVENT_FEED";

// Signup / Login
export const SET_PASSWORD = "SET_PASSWORD";
export const SET_CONFIRM_PASSWORD = "SET_CONFIRM_PASSWORD";
export const SET_EMAIL = "SET_EMAIL";
export const SUBMIT_LOGIN = "SUBMIT_LOGIN";
export const SUBMIT_SIGNUP = "SUBMIT_SIGNUP";
export const SET_SIGNUP_ERROR = "SET_SIGNUP_ERROR";
export const SET_LOGIN_ERROR = "SET_LOGIN_ERROR";
export const SUBMIT_GOOGLE_OAUTH2_SIGNUP = "SUBMIT_GOOGLE_OAUTH2_SIGNUP";
export const SUBMIT_GOOGLE_OAUTH2_LOGIN = "SUBMIT_GOOGLE_OAUTH2_LOGIN";
export const INIT_USERS = "INIT_USERS";
export const SET_USER = "SET_USER";
export const SET_TOKEN = "SET_TOKEN";
export const LOGOUT_USER = "LOGOUT_USER";
export const CLEAR_TOKEN = "CLEAR_TOKEN";

// User Events Calender
export const SET_USER_EVENT_CALENDER = "SET_USER_EVENT_CALENDER";
